FROM alpine:3

LABEL author="Raka Nofriandi Putra"
LABEL company="Ampera Ajo Kiri" website="https://www.ajokiri.site"

RUN mkdir hello
RUN echo "hello world" > hello/world.txt

CMD cat hello/world.txt